cache:
  node:
    fields:
      - name
  async: thread
model:
  graph-entity:
    search-key: name
  embedding: 
    model-name: /Users/cyx/Downloads/iic/nlp_corom_sentence-embedding_chinese-base
    device: cpu
# C:/Users/李衍铭/.cache/modelscope/hub/iic/nlp_corom_sentence-embedding_chinese-base

database:
  neo4j:
    url: bolt://localhost:7687
    database: neo4j
    username: neo4j
    # 注意数字用引号引起来
    password: TangZiYe20050316
